version: '3.7'
services:
  app:
    container_name: financebackend
    restart: always
    build: .
    ports: 
      - '8000:8000'
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017